const systemTypes = ['SAM', 'TBM', 'EW', 'EMW', 'MARITIME'];
const systemNames = {
    'SAM': ['RBG-6', 'RBG-15', 'BG-5', 'RBG-12'],
    'TBM': ['BG-10', 'RBG-11'],
    'EW': ['SAV'],
    'EMW': ['JX'],
    'MARITIME': ['CG', 'DD', 'FF']
};

const emitters = [
    { "systemType": "SAM", "systemName": "RBG-6", "emitterName": "COOKIE CUTTER", "elnot": "F5A3B", "freq": "9178" },
    { "systemType": "SAM", "systemName": "RBG-6", "emitterName": "FOOTBALL LACE", "elnot": "3U53T", "freq": "4890" },
    { "systemType": "SAM", "systemName": "RBG-6", "emitterName": "FISH FINDER", "elnot": "ZMWDB", "freq": "1988" },
    { "systemType": "SAM", "systemName": "RBG-15", "emitterName": "SPEAKER WIRE", "elnot": "BRAAW", "freq": "4954" },
    { "systemType": "SAM", "systemName": "RBG-15", "emitterName": "BIRD SEED", "elnot": "LK0YO", "freq": "7763" },
    { "systemType": "SAM", "systemName": "RBG-15", "emitterName": "COFFEE BEAN", "elnot": "BVG9T", "freq": "5350" },
    { "systemType": "SAM", "systemName": "RBG-15", "emitterName": "SALAD DRESSING", "elnot": "PRL97", "freq": "4293" },
    { "systemType": "SAM", "systemName": "BG-5", "emitterName": "THROAT CUTTER", "elnot": "Y3VYK", "freq": "6399" },
    { "systemType": "SAM", "systemName": "BG-5", "emitterName": "GREY MOUSE", "elnot": "EC7GD", "freq": "7896" },
    { "systemType": "SAM", "systemName": "BG-5", "emitterName": "DOG HOUSE", "elnot": "PEEV6", "freq": "6783" },
    { "systemType": "SAM", "systemName": "BG-5", "emitterName": "RED LIGHT", "elnot": "2SFVU", "freq": "6407" },
    { "systemType": "SAM", "systemName": "RBG-12", "emitterName": "STOP SIGN", "elnot": "QHRK3", "freq": "5331" },
    { "systemType": "SAM", "systemName": "RBG-12", "emitterName": "SHARP SWORD", "elnot": "CF9GI", "freq": "128" },
    { "systemType": "SAM", "systemName": "RBG-12", "emitterName": "SHIRT SLEEVE", "elnot": "YCSKZ", "freq": "3493" },
    { "systemType": "SAM", "systemName": "RBG-12", "emitterName": "HAND MIRROR", "elnot": "DODWI", "freq": "7927" },
    { "systemType": "TBM", "systemName": "BG-10", "emitterName": "COAT HANGER", "elnot": "EM162", "freq": "5160" },
    { "systemType": "TBM", "systemName": "BG-10", "emitterName": "STEAK KNIFE", "elnot": "A2YLM", "freq": "9783" },
    { "systemType": "TBM", "systemName": "BG-10", "emitterName": "BOOK SHELF", "elnot": "G7X2C", "freq": "2788" },
    { "systemType": "TBM", "systemName": "BG-10", "emitterName": "HAMSTER WHEEL", "elnot": "9BOND", "freq": "2128" },
    { "systemType": "TBM", "systemName": "RBG-11", "emitterName": "GAME CARTRIDGE", "elnot": "A6FQ1", "freq": "8074" },
    { "systemType": "TBM", "systemName": "RBG-11", "emitterName": "YELLOW FLOWER", "elnot": "1OLU6", "freq": "6938" },
    { "systemType": "TBM", "systemName": "RBG-11", "emitterName": "JAM JAR", "elnot": "4592B", "freq": "4610" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "DESK CHAIR", "elnot": "3LQUQ", "freq": "9614" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "TIN CAN", "elnot": "I6MHL", "freq": "4391" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "CHICKEN FOOT", "elnot": "72L0Y", "freq": "8890" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "NEEDLE EYE", "elnot": "U9JCV", "freq": "8190" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "ICE PICK", "elnot": "PF8CM", "freq": "8092" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "CLOCK FACE", "elnot": "ZPTWL", "freq": "554" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "BRICK HOUSE", "elnot": "YPTSF", "freq": "9736" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "RED DAWN", "elnot": "VSZ6W", "freq": "1734" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "BLACK SAIL", "elnot": "GAVN6", "freq": "7244" },
    { "systemType": "EW", "systemName": "SAV", "emitterName": "TOE RING", "elnot": "H1X32", "freq": "3613" },
    { "systemType": "EMW", "systemName": "JX", "emitterName": "CHECK BOOK", "elnot": "NNWI0", "freq": "1986" },
    { "systemType": "EMW", "systemName": "JX", "emitterName": "SAND GLASS", "elnot": "5KM9Z", "freq": "3247" },
    { "systemType": "EMW", "systemName": "JX", "emitterName": "SNAIL SHELL", "elnot": "W1E5S", "freq": "278" },
    { "systemType": "MARITIME", "systemName": "CG", "emitterName": "GOOSE", "elnot": "FD658", "freq": "1489" },
    { "systemType": "MARITIME", "systemName": "CG", "emitterName": "GOSLING", "elnot": "FL628", "freq": "1102" },
    { "systemType": "MARITIME", "systemName": "DD", "emitterName": "DUCK", "elnot": "FM858", "freq": "1147" },
    { "systemType": "MARITIME", "systemName": "DD", "emitterName": "DUCKLING", "elnot": "FJ111", "freq": "3325" },
    { "systemType": "MARITIME", "systemName": "FF", "emitterName": "PELICAN", "elnot": "FV828", "freq": "1001" },
    { "systemType": "MARITIME", "systemName": "FF", "emitterName": "SEAGULL", "elnot": "FO665", "freq": "1247" }
];
